/**
 * properties.js — server.properties / eula.txt の読み書き
 *
 * MCはserver.propertiesを生のUTF-8・CRLFで読み書きする(\uエスケープなし。実機で確認済み)。
 * Java系のpropertiesライブラリはISO-8859-1+\uエスケープで往復して日本語ワールド名を壊すので使わない。
 * 編集は「触った行だけ作り直し、他の行はバイト単位でそのまま」— コメント・順序・改行コードを保つ。
 */
'use strict';

const fs = require('fs');
const path = require('path');

function stamp() {
  return new Date().toISOString();
}

/* ── 新規作成 ─────────────────────── */

function writeInitial(dir, { port, motd }) {
  const lines = [
    '#Minecraft server properties',
    `#Generated by SabaKobo ${stamp()}`,
    `server-port=${port}`,
    `motd=${motd}`
  ];
  fs.writeFileSync(path.join(dir, 'server.properties'), lines.join('\r\n') + '\r\n', 'utf8');
}

/* EULA同意はUIのチェックボックスを通ってからのみ呼ばれる(勝手に同意しない) */
function writeEula(dir) {
  const lines = [
    '#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).',
    `#Generated by SabaKobo ${stamp()}`,
    'eula=true'
  ];
  fs.writeFileSync(path.join(dir, 'eula.txt'), lines.join('\r\n') + '\r\n', 'utf8');
}

/* ── 解析(キーだけエスケープ処理。値は素通し=MC自身が素で書くため) ── */

function unescapeKey(k) { return k.replace(/\\([\\=:#!])/g, '$1'); }
function escapeKey(k) { return k.replace(/([\\=:#!])/g, '\\$1'); }

/* 行ごとに {raw} か {raw, key, value} へ。改行コードも検出して返す */
function parseText(text) {
  const nl = text.includes('\r\n') ? '\r\n' : '\n';
  const entries = text.split(/\r?\n/).map(raw => {
    const t = raw.trim();
    if (!t || t.startsWith('#') || t.startsWith('!')) return { raw };
    const m = raw.match(/^((?:\\.|[^=:\\])+)[=:](.*)$/);
    if (!m) return { raw };
    return { raw, key: unescapeKey(m[1].trim()), value: m[2] };
  });
  return { nl, entries };
}

/* ── 読み ─────────────────────────── */

function read(dir) {
  const p = path.join(dir, 'server.properties');
  if (!fs.existsSync(p)) return { ok: true, exists: false, values: {}, keys: [] };
  const { entries } = parseText(fs.readFileSync(p, 'utf8'));
  const values = {};
  const keys = [];
  for (const e of entries) {
    if (e.key !== undefined && !(e.key in values)) { values[e.key] = e.value; keys.push(e.key); }
  }
  return { ok: true, exists: true, values, keys };
}

/* ── 書き(触った行だけ差し替え) ─────────── */

function update(dir, changes) {
  const p = path.join(dir, 'server.properties');
  if (!fs.existsSync(p)) throw new Error('server.properties がまだありません(初回起動が必要です)');
  const text = fs.readFileSync(p, 'utf8');
  const { nl, entries } = parseText(text);
  const remaining = { ...changes };
  const out = entries.map(e => {
    if (e.key !== undefined && e.key in remaining) {
      const v = String(remaining[e.key]);
      delete remaining[e.key];
      return escapeKey(e.key) + '=' + v;
    }
    return e.raw; /* 触らない行はバイトそのまま */
  });
  for (const [k, v] of Object.entries(remaining)) out.push(escapeKey(k) + '=' + String(v)); /* 無いキーは末尾へ */
  const tmp = p + '.tmp';
  fs.writeFileSync(tmp, out.join(nl), 'utf8');
  fs.renameSync(tmp, p);
}

module.exports = { writeInitial, writeEula, parseText, read, update };
